name: 💬 Feedback
description: Share general feedback or impressions
labels: ["feedback"]
body:
  - type: textarea
    id: feedback
    attributes:
      label: Your feedback
      description: What do you like, dislike, or wish were different?
    validations:
      required: true
  - type: input
    id: device
    attributes:
      label: Device (optional)
      placeholder: "e.g. Huawei Mate 10 Pro"
    validations:
      required: false
